export const CREATE_TEAM = 'CREATE_TEAM';
export const SET_CURRENT_TEAM = 'SET_CURRENT_TEAM';
export const UPDATE_TEAM = 'UPDATE_TEAM';
export const REMOVE_TEAM_MEMBER = 'REMOVE_TEAM_MEMBER';
export const DELETE_TEAM = 'DELETE_TEAM';
